baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Portfolio Site'
theme = 'raditian'

# SEO Configuration
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = false

# Sitemap Configuration
[sitemap]
  changefreq = 'monthly'
  priority = 0.5
  filename = 'sitemap.xml'

# Markup Configuration for SEO
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow HTML in markdown
  [markup.highlight]
    style = "github"
    lineNos = false
    codeFences = true
    guessSyntax = true
    noClasses = false

# Privacy Configuration
[privacy]
  [privacy.googleAnalytics]
    respectDoNotTrack = true
    anonymizeIP = true
    useSessionStorage = true
  [privacy.youtube]
    privacyEnhanced = true

# Performance Configuration
[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
    [minify.tdewolff.css]
      keepCSS2 = false
    [minify.tdewolff.js]
      keepVarNames = false

# Output Formats for SEO
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"
    
# Related Content Configuration
[related]
  threshold = 80
  includeNewer = true
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 200
  [[related.indices]]
    name = "date"
    weight = 10

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"
  [[params.plugins.js]]
  URL = "js/analytics-events.js"

# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4

  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4

[params]
  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  [params.logo]
    text1 = "Your"
    text2 = "Portfolio"

  [params.footer]
    copyright = "© Your Portfolio. All rights reserved."
